import { Creature, CreatureType, TimeOfDay } from './types';

export const CREATURES: Creature[] = [
  {
    id: '001',
    name: '綿あめ犬',
    latinName: 'Canis Saccharum',
    type: CreatureType.Park,
    activeTime: [TimeOfDay.Day, TimeOfDay.Sunset],
    imageUrl: 'https://picsum.photos/id/1025/500/500', 
    shortDesc: '晴天時の公園に出現。体毛が高純度の糖分（綿あめ）で構成されており、湿度が高いと溶解してしまう。',
    dangerLevel: 1,
  },
  {
    id: '002',
    name: '豆電球ムシ',
    latinName: 'Lampyridae Volt',
    type: CreatureType.Garden,
    activeTime: [TimeOfDay.Sunset, TimeOfDay.Night],
    imageUrl: 'https://picsum.photos/id/535/500/500', 
    shortDesc: '腹部がガラス質の電球状に進化した甲虫。夜間、フィラメントを振動させて発光し、仲間と交信する。',
    dangerLevel: 2,
  },
  {
    id: '003',
    name: '水面すべり猫',
    latinName: 'Felis Hydro',
    type: CreatureType.Water,
    activeTime: [TimeOfDay.Day, TimeOfDay.Morning],
    imageUrl: 'https://picsum.photos/id/40/500/500', 
    shortDesc: '表面張力を操り、水面を滑走する猫。肉球は撥水性が高く、浮き輪のような弾力を持つ。',
    dangerLevel: 2,
  },
  {
    id: '004',
    name: 'しおり竜',
    latinName: 'Draco Bookmarkus',
    type: CreatureType.House,
    activeTime: [TimeOfDay.Night, TimeOfDay.Any],
    imageUrl: 'https://picsum.photos/id/1033/500/500', 
    shortDesc: '読みかけの書籍に擬態する極小ドラゴン。物語の内容を吸収し、就寝中の人間に夢として見せることがある。',
    dangerLevel: 1,
  },
  {
    id: '005',
    name: 'Wi-Fi妖精',
    latinName: 'Spiritus Wireless',
    type: CreatureType.House,
    activeTime: [TimeOfDay.Any],
    imageUrl: 'https://picsum.photos/id/804/500/500', 
    shortDesc: 'Wi-Fiルーター周辺に発生する光の粒子。機嫌が良いと通信速度をブーストするが、怒ると接続を遮断する。',
    dangerLevel: 3,
  },
  {
    id: '006',
    name: 'シャドー・ドッグ',
    latinName: 'Umbra Canis',
    type: CreatureType.Garden,
    activeTime: [TimeOfDay.Sunset],
    imageUrl: 'https://picsum.photos/id/237/500/500', 
    shortDesc: '夕暮れ時に伸びた影から実体化する黒い犬。物理的な攻撃は通じないが、撫でると温もりを感じる。',
    dangerLevel: 2,
  },
   {
    id: '007',
    name: 'アスファルト亀',
    latinName: 'Testudo Cementum',
    type: CreatureType.Park,
    activeTime: [TimeOfDay.Day, TimeOfDay.Morning],
    imageUrl: 'https://picsum.photos/id/837/500/500',
    shortDesc: '甲羅がコンクリートと同化している亀。道路のひび割れに擬態して獲物を待つ。強度は鉄に匹敵する。',
    dangerLevel: 1,
  },
  {
    id: '008',
    name: 'ドリーム・バブル魚',
    latinName: 'Piscis Bulla',
    type: CreatureType.Water,
    activeTime: [TimeOfDay.Morning, TimeOfDay.Day],
    imageUrl: 'https://picsum.photos/id/1053/500/500', 
    shortDesc: '七色に輝く泡を吐き出す魚。泡の表面には、その魚が見た「過去の風景」が映し出されるという。',
    dangerLevel: 3,
  },
  {
    id: '009',
    name: 'ミスト・スパイダー',
    latinName: 'Aranea Nebula',
    type: CreatureType.Mystery,
    activeTime: [TimeOfDay.Morning],
    imageUrl: 'https://picsum.photos/id/166/500/500', 
    shortDesc: '濃霧の朝にのみ出現。水滴で構成された巣を張る。巣に触れると霧散してしまうため、捕獲は困難。',
    dangerLevel: 4,
  }
];

export const APP_NAME = "パラレル生物図鑑";